---
- hosts: all
  gather_facts: no
  sudo: yes

  vars:
    - APP_DIR: /vagrant
    - APP_PORT: 3000
    - APP_NAME: django_app
    - APP_STATIC_DIR: "{{ APP_DIR }}/static"

  tasks:

    - name: Install system packages
      apt: pkg={{ item }} state=present
      with_items:
        - python-pip
        - make

    - name: Create app nginx site configuration
      template: src=./templates/app_nginx.site.conf.j2 
                dest=/etc/nginx/sites-available/{{ APP_NAME }}
      notify: 
        - restart nginx

    - name: Create link to enable nginx site
      file: path=/etc/nginx/sites-enabled/{{ APP_NAME }}
            src=/etc/nginx/sites-available/{{ APP_NAME }}
            state=link
      notify:
        - restart nginx

    - name: restart nginx
      service: name=nginx state=reloaded

    - name: Install django app requirements.
      pip: >
        requirements={{ APP_DIR }}/requirements/development.txt

    - name: migrate db
      django_manage: >
        app_path={{ APP_DIR }} 
        settings=settings.development
        command={{ item }} 
      with_items:
        - validate
        - collectstatic
        - syncdb
        - migrate

    - name: runserver
      command: make run && make run2 chdir=/vagrant

  handlers:

    - name: restart nginx
      service: name=nginx state=reloaded

# a good resource: https://www.howtoforge.com/using-geoip-with-nginx-on-ubuntu-12.04