---
- hosts: all
  gather_facts: no
  sudo: yes

  vars:
    - APP_DIR: /vagrant
    - APP_PORT: 3000
    - APP_NAME: django_app
    - APP_STATIC_DIR: "{{ APP_DIR }}/static"

  tasks:

    - name: Install system packages
      apt: pkg={{ item }} state=present
      with_items:
        - python-pip
        - make
        - curl
        - supervisor

    - name: Create app nginx site configuration
      template: src=./templates/app_nginx.site.conf.j2 
                dest=/etc/nginx/sites-available/{{ APP_NAME }}
      notify: 
        - restart nginx

    - name: Create link to enable nginx site
      file: path=/etc/nginx/sites-enabled/{{ APP_NAME }}
            src=/etc/nginx/sites-available/{{ APP_NAME }}
            state=link
      notify:
        - restart nginx

    - name: restart nginx
      service: name=nginx state=reloaded

    - name: Install django app requirements.
      pip: >
        requirements={{ APP_DIR }}/requirements/development.txt

    - name: migrate db
      django_manage: >
        app_path={{ APP_DIR }} 
        settings=settings.development
        command={{ item }} 
      with_items:
        - validate
        - collectstatic
        - syncdb
        - migrate

    - name: Configure supervisord
      template: src=templates/supervisor.j2 
                dest={{ APP_DIR }}/supervisord.conf
      notify: 
        - restart supervisord

    - name: Kill all supervisord
      command: killall supervisord
      ignore_errors: yes
      sudo: yes
      sudo_user: root

    - name: Wait for supervisor to clean up and exit
      pause: seconds=8

    - name: Start supervisord
      command: supervisord -c {{ APP_DIR }}/supervisord.conf
      sudo: yes
      sudo_user: root

  handlers:

    - name: restart nginx
      service: name=nginx state=restarted
      sudo: yes

    - name: restart supervisord
      service: name=supervisor state=restarted enabled=yes
      sudo: yes

# a good resource: https://www.howtoforge.com/using-geoip-with-nginx-on-ubuntu-12.04