---
- hosts: all
  gather_facts: no
  sudo: yes

  vars:
    - APP_DIR: /vagrant
    - APP_PORT: 4700

  tasks:

    - name: Install system packages
      apt: pkg={{ item }} state=present
      with_items:
        - python-pip
        - make

    - name: Install django app requirements.
      pip: >
        requirements={{ APP_DIR }}/requirements/development.txt

    - name: migrate db
      django_manage: >
        app_path={{ APP_DIR }} 
        settings=settings.development
        command={{ item }} 
      with_items:
        - validate
        - collectstatic
        - syncdb
        - migrate

    - name: runserver
      command: make run chdir=/vagrant

  handlers:

    - name: restart nginx
      service: name=nginx state=reloaded

# a good resource: https://www.howtoforge.com/using-geoip-with-nginx-on-ubuntu-12.04